### ISSUE TITLE
Rebuild of texworks to include texlive 2020

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.tug.texworks#2]
Hi,

I updated the texlive package to texlive 2020. I think you have however demand a rebuild of texworks under [https://flathub.org/builds/](https://flathub.org/builds/) that texworks includes it and delivers it to the users.

Regards

**Comment by jakobjakobson13** [comment]
Thanks for the rebuilding. The compilation of `small2e.tex` worked with TeXLive 20202s version of pdflatex, xelatex and lualatex.

**Comment by stloeffler** [comment]
No problem, thanks for testing. Closing.
