### ISSUE TITLE
Application not opening in Linux Mint 21.3 Cinnamon

### ISSUE THREAD

**Issue by mrpoet2** [flathub/org.tug.texworks#48]
When using the gui it doesn't open at all. 

When trying to start it from CLI:
`flatpak run org.tug.texworks`

I get the following error.
`texworks: symbol lookup error: texworks: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6`

This is a fresh install of Linux Mint Cinnamon. I hope there is a workaround.

Installed among others: 
`org.freedesktop.Sdk.Extension.texlive 20210325 23.08`                  
`org.kde.Platform  6.6 system`
`org.tug.texworks  0.6.9 stable system`

Thanks,
George

**Comment by jakobjakobson13** [comment]
I can confirm this issue.

**Comment by stloeffler** [comment]
This seems to have been caused by a bug in the KDE framework. The bug has since been fixed and I just rebuilt the TeXworks package, so if you update your flatpak packages the issue should hopefully been resolved.
